haiku build fix proposal.
tormol/uds pull request #7
Opened 2022-11-02 19:43 UTC by devnexen

Disabling non existing features and flags (close on exec). Fixing ControlLen type.

2022-11-04 13:15 UTC, tormol requested changes
Looks good.
Is there a rustup target for haiku? (to check that it builds).

2022-11-04 13:22 UTC, devnexen commented on src/helpers.rs
> +#[cfg(not(target_os = "haiku"))]
works for me.

2022-11-04 13:22 UTC, devnexen commented
> Looks good. Is there a rustup target for haiku? (to check that it builds).

no unfortunately

2022-11-08 21:08 UTC, tormol approved these changes

2022-11-08 21:09 UTC, tormol commented
I've fixed the MSRV and macOS build failures on master. You just need to rebase.

2022-11-08 22:30 UTC, merged

2023-08-14 19:05 UTC, tormol commented
This is finally released! in 0.3.0.

2023-08-14 19:46 UTC, devnexen commented
Hey ! I forgot about this one :)